//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 03:04:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "LoadContainerType.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.nl.tue.ieis.get.event.type.loadContainerType;
