//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.29 at 02:50:21 PM CEST 
//


package main.java.nl.tue.ieis.get.event.type.predictedDeadlineViolatio;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operatorId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="distanceRemaining" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="nodeDeadline" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eta" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="predictedDelay" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operatorId",
    "timestamp",
    "longitude",
    "latitude",
    "distanceRemaining",
    "nodeDeadline",
    "eta",
    "predictedDelay"
})
@XmlRootElement(name = "PredictedDeadlineViolationEvent")
public class PredictedDeadlineViolationEvent {

    @XmlElement(required = true)
    protected BigInteger operatorId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String timestamp;
    protected double longitude;
    protected double latitude;
    protected long distanceRemaining;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String nodeDeadline;
    protected String eta;
    protected long predictedDelay;

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOperatorId(BigInteger value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the distanceRemaining property.
     * 
     */
    public long getDistanceRemaining() {
        return distanceRemaining;
    }

    /**
     * Sets the value of the distanceRemaining property.
     * 
     */
    public void setDistanceRemaining(long value) {
        this.distanceRemaining = value;
    }

    /**
     * Gets the value of the nodeDeadline property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getNodeDeadline() {
        return nodeDeadline;
    }

    /**
     * Sets the value of the nodeDeadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNodeDeadline(String value) {
        this.nodeDeadline = value;
    }

    /**
     * Gets the value of the eta property.
     * 
     */
    public String getEta() {
        return eta;
    }

    /**
     * Sets the value of the eta property.
     * 
     */
    public void setEta(String value) {
        this.eta = value;
    }

    /**
     * Gets the value of the predictedDelay property.
     * 
     */
    public long getPredictedDelay() {
        return predictedDelay;
    }

    /**
     * Sets the value of the predictedDelay property.
     * 
     */
    public void setPredictedDelay(long value) {
        this.predictedDelay = value;
    }

}
