//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 08:57:04 PM CEST 
//


package main.java.nl.tue.ieis.get.event.type.flightDiversionDetected;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departurelatitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="departurelongitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arrivallatitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="arrivallongitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="certainty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aircraftId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="flightCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightId",
    "origin",
    "departurelatitude",
    "departurelongitude",
    "destination",
    "arrivallatitude",
    "arrivallongitude",
    "certainty",
    "aircraftId",
    "flightCode",
    "latitude",
    "longitude",
    "timestamp"
})
@XmlRootElement(name = "FlightDiversion")
public class FlightDiversion {

    @XmlElement(required = true)
    protected BigInteger flightId;
    @XmlElement(required = true)
    protected String origin;
    protected double departurelatitude;
    protected double departurelongitude;
    @XmlElement(required = true)
    protected String destination;
    protected double arrivallatitude;
    protected double arrivallongitude;
    @XmlElement(required = true)
    protected String certainty;
    @XmlElement(required = true)
    protected BigInteger aircraftId;
    @XmlElement(required = true)
    protected String flightCode;
    protected double latitude;
    protected double longitude;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String timestamp;

    /**
     * Gets the value of the flightId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlightId() {
        return flightId;
    }

    /**
     * Sets the value of the flightId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlightId(BigInteger value) {
        this.flightId = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the departurelatitude property.
     * 
     */
    public double getDeparturelatitude() {
        return departurelatitude;
    }

    /**
     * Sets the value of the departurelatitude property.
     * 
     */
    public void setDeparturelatitude(double value) {
        this.departurelatitude = value;
    }

    /**
     * Gets the value of the departurelongitude property.
     * 
     */
    public double getDeparturelongitude() {
        return departurelongitude;
    }

    /**
     * Sets the value of the departurelongitude property.
     * 
     */
    public void setDeparturelongitude(double value) {
        this.departurelongitude = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the arrivallatitude property.
     * 
     */
    public double getArrivallatitude() {
        return arrivallatitude;
    }

    /**
     * Sets the value of the arrivallatitude property.
     * 
     */
    public void setArrivallatitude(double value) {
        this.arrivallatitude = value;
    }

    /**
     * Gets the value of the arrivallongitude property.
     * 
     */
    public double getArrivallongitude() {
        return arrivallongitude;
    }

    /**
     * Sets the value of the arrivallongitude property.
     * 
     */
    public void setArrivallongitude(double value) {
        this.arrivallongitude = value;
    }

    /**
     * Gets the value of the certainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertainty() {
        return certainty;
    }

    /**
     * Sets the value of the certainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertainty(String value) {
        this.certainty = value;
    }

    /**
     * Gets the value of the aircraftId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAircraftId() {
        return aircraftId;
    }

    /**
     * Sets the value of the aircraftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAircraftId(BigInteger value) {
        this.aircraftId = value;
    }

    /**
     * Gets the value of the flightCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightCode() {
        return flightCode;
    }

    /**
     * Sets the value of the flightCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightCode(String value) {
        this.flightCode = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

}
