//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.16 at 02:29:15 PM CEST 
//


package main.java.nl.tue.ieis.get.event.type.roadTraffic;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idAtProvider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areaCenter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="areaPolygon">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="coordinate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="longitute" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="magnitude" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="cause" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roadsAffected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idAtProvider",
    "areaCenter",
    "areaPolygon",
    "timestamp",
    "type",
    "magnitude",
    "description",
    "length",
    "delay",
    "cause",
    "roadsAffected",
    "provider",
    "identifier"
})
@XmlRootElement(name = "RoadTrafficEvent")
public class RoadTrafficEvent {

    @XmlElement(required = true)
    protected String idAtProvider;
    @XmlElement(required = true)
    protected RoadTrafficEvent.AreaCenter areaCenter;
    @XmlElement(required = true)
    protected RoadTrafficEvent.AreaPolygon areaPolygon;
//    XMLGregorianCalendar
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String timestamp;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected int magnitude;
    @XmlElement(required = true)
    protected String description;
    protected int length;
    protected int delay;
    @XmlElement(required = true)
    protected String cause;
    @XmlElement(required = true)
    protected String roadsAffected;
    @XmlElement(required = true)
    protected String provider;
    @XmlElement(required = true)
    protected String identifier;

    /**
     * Gets the value of the idAtProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAtProvider() {
        return idAtProvider;
    }

    /**
     * Sets the value of the idAtProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAtProvider(String value) {
        this.idAtProvider = value;
    }

    /**
     * Gets the value of the areaCenter property.
     * 
     * @return
     *     possible object is
     *     {@link RoadTrafficEvent.AreaCenter }
     *     
     */
    public RoadTrafficEvent.AreaCenter getAreaCenter() {
        return areaCenter;
    }

    /**
     * Sets the value of the areaCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadTrafficEvent.AreaCenter }
     *     
     */
    public void setAreaCenter(RoadTrafficEvent.AreaCenter value) {
        this.areaCenter = value;
    }

    /**
     * Gets the value of the areaPolygon property.
     * 
     * @return
     *     possible object is
     *     {@link RoadTrafficEvent.AreaPolygon }
     *     
     */
    public RoadTrafficEvent.AreaPolygon getAreaPolygon() {
        return areaPolygon;
    }

    /**
     * Sets the value of the areaPolygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadTrafficEvent.AreaPolygon }
     *     
     */
    public void setAreaPolygon(RoadTrafficEvent.AreaPolygon value) {
        this.areaPolygon = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the magnitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getMagnitude() {
        return magnitude;
    }

    /**
     * Sets the value of the magnitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMagnitude(int value) {
        this.magnitude = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     */
    public int getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     */
    public void setDelay(int value) {
        this.delay = value;
    }

    /**
     * Gets the value of the cause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCause() {
        return cause;
    }

    /**
     * Sets the value of the cause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCause(String value) {
        this.cause = value;
    }

    /**
     * Gets the value of the roadsAffected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadsAffected() {
        return roadsAffected;
    }

    /**
     * Sets the value of the roadsAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadsAffected(String value) {
        this.roadsAffected = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "longitude",
        "latitude"
    })
    public static class AreaCenter {

        protected double longitude;
        protected double latitude;

        /**
         * Gets the value of the longitude property.
         * 
         */
        public double getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         */
        public void setLongitude(double value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         */
        public double getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         */
        public void setLatitude(double value) {
            this.latitude = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="coordinate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="longitute" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "coordinate"
    })
    public static class AreaPolygon {

        @XmlElement(required = true)
        protected RoadTrafficEvent.AreaPolygon.Coordinate coordinate;

        /**
         * Gets the value of the coordinate property.
         * 
         * @return
         *     possible object is
         *     {@link RoadTrafficEvent.AreaPolygon.Coordinate }
         *     
         */
        public RoadTrafficEvent.AreaPolygon.Coordinate getCoordinate() {
            return coordinate;
        }

        /**
         * Sets the value of the coordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoadTrafficEvent.AreaPolygon.Coordinate }
         *     
         */
        public void setCoordinate(RoadTrafficEvent.AreaPolygon.Coordinate value) {
            this.coordinate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="longitute" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "longitute",
            "latitude"
        })
        public static class Coordinate {

            protected double longitute;
            protected double latitude;

            /**
             * Gets the value of the longitute property.
             * 
             */
            public double getLongitute() {
                return longitute;
            }

            /**
             * Sets the value of the longitute property.
             * 
             */
            public void setLongitute(double value) {
                this.longitute = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             */
            public double getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             */
            public void setLatitude(double value) {
                this.latitude = value;
            }

        }

    }

}
