//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 02:58:15 PM CEST 
//


package main.java.nl.tue.ieis.get.event.type.traceNew;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.nl.tue.ieis.get.event.publisher.type.traceNew package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.nl.tue.ieis.get.event.publisher.type.traceNew
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link Trace.Addressmatch }
     * 
     */
    public Trace.Addressmatch createTraceAddressmatch() {
        return new Trace.Addressmatch();
    }

    /**
     * Create an instance of {@link Trace.Property }
     * 
     */
    public Trace.Property createTraceProperty() {
        return new Trace.Property();
    }

    /**
     * Create an instance of {@link Trace.Addressmatch.Coordinate }
     * 
     */
    public Trace.Addressmatch.Coordinate createTraceAddressmatchCoordinate() {
        return new Trace.Addressmatch.Coordinate();
    }

    /**
     * Create an instance of {@link Trace.Addressmatch.Address }
     * 
     */
    public Trace.Addressmatch.Address createTraceAddressmatchAddress() {
        return new Trace.Addressmatch.Address();
    }

}
