//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 12:46:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "VehiclePosition.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.nl.tue.ieis.get.event.type.vehiclePosition;
