//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 02:55:18 PM CEST 
//


package main.java.nl.tue.ieis.get.event.type.activitiLog;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }


    public ActivityLog createActivityLog() {
        return new ActivityLog();
    }

}
